name: Correctness test for latest repository versions

on:
  push:
  schedule:
    - cron: "0 3,15 * * *"  # every day at 3am and 3pm

env:
  RSCPP_VERSION: "2024.1.2"

jobs:
  generate_matrix:
    name: Generate build matrix
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: python .github/build_projects_matrix.py ./projects.json ./proj-config correctness-latest ${{github.event_name}} ${{contains(github.event.head_commit.message, '[ci-all]')}} >> $GITHUB_OUTPUT

  run_correctness_test:
    needs: generate_matrix
    runs-on: ${{matrix.os}}
    name: Run test on ${{matrix.project}}:${{matrix.branch}} (${{matrix.cmake_gen}})

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install CI python dependencies
        run: pip install -r .github/ci_requirements.txt

      - name: Install .NET tools
        id: install-tool
        shell: bash
        run: python .github/tool_installer.py ${{ env.RSCPP_VERSION }}

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run correctness test
        id: inspect-code
        shell: bash
        run: |
          [[ "${{matrix.VsInstallRoot}}" ]] && export VsInstallRoot="${{matrix.VsInstallRoot}}"
          [[ "${{matrix.VCTargetsPath}}" ]] && export VCTargetsPath="${{matrix.VCTargetsPath}}"
          echo "RSCPP_WORK_DIR=$RUNNER_TEMP/projects/${{matrix.project}}/${{matrix.rscpp_work_dir}}" >> $GITHUB_OUTPUT
          echo "REPORT_PATH=$RUNNER_TEMP/report.json" >> $GITHUB_OUTPUT
          python CorrectnessTest.py \
            --project ${{matrix.project}}:${{matrix.branch}} \
            --vcpkg-dir $VCPKG_INSTALLATION_ROOT \
            --build-dir ${{ steps.install-tool.outputs.TOOL_DIR }} \
            --projects-cache $RUNNER_TEMP/projects \
            --supported-generators ${{matrix.cmake_gen}} \
            --report-path $RUNNER_TEMP/report.json \
            --ci \
            --verbose

      - name: Save logs
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.project}}-${{matrix.branch}}-${{matrix.cmake_gen}}-logs
          path: "${{ steps.inspect-code.outputs.RSCPP_WORK_DIR }}/resharper-*"

      - name: Upload reports'
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.project}}-${{matrix.branch}}-${{matrix.cmake_gen}}-report
          path: "${{ steps.inspect-code.outputs.REPORT_PATH }}"
          retention-days: 1

  collect_reports:
    needs: run_correctness_test
    if: success() || failure()
    runs-on: ubuntu-22.04
    name: Collect reports

    steps:
    - uses: actions/checkout@v4

    - name: Clone report branch
      uses: actions/checkout@v4
      with:
        ref: "gh-pages"
        path: gh-pages

    - name: Download reports' artifacts
      uses: actions/download-artifact@v4
      with:
        path: downloaded_artifacts

    - name: Update report
      shell: bash
      run: python .github/save_stats.py ./downloaded_artifacts $GITHUB_WORKSPACE/gh-pages

    - name: Commit report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
