name: Correctness test for latest repository versions

on:
  push:
  schedule:
    - cron: "0 */4 * * *"  # every 4 hours

env:
  RSCPP_VERSION: 2023.1.0

jobs:
  generate_matrix:
    name: Generate build matrix
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - id: set-matrix
        run: python .github/build_projects_matrix.py ./projects.json ./proj-config correctness-latest ${{github.event_name}} >> $GITHUB_OUTPUT

  run_correctness_test:
    needs: generate_matrix
    runs-on: ${{matrix.os}}
    name: Run test on ${{matrix.project}}:${{matrix.branch}} (${{matrix.cmake_gen}})

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3

      - name: Install R++
        run: dotnet tool update --global JetBrains.ReSharper.GlobalTools --version ${{ env.RSCPP_VERSION }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run correctness test
        id: inspect-code
        shell: bash
        run: |
          [[ "${{matrix.VsInstallRoot}}" ]] && export VsInstallRoot="${{matrix.VsInstallRoot}}"
          [[ "${{matrix.VCTargetsPath}}" ]] && export VCTargetsPath="${{matrix.VCTargetsPath}}"
          python CorrectnessTest.py \
            --project ${{matrix.project}}:${{matrix.branch}} \
            --vcpkg-dir $VCPKG_INSTALLATION_ROOT \
            --build-dir $USERPROFILE/.dotnet/tools/.store/jetbrains.resharper.globaltools/${{ env.RSCPP_VERSION }}/jetbrains.resharper.globaltools/${{ env.RSCPP_VERSION }}/tools/netcoreapp3.1/any \
            --projects-cache $RUNNER_TEMP/projects \
            --supported-generators ${{matrix.cmake_gen}} \
            --report-path $RUNNER_TEMP/report.json \
            --verbose
          echo "BUILD_DIR=$RUNNER_TEMP/projects/${{matrix.project}}/build-${{matrix.cmake_gen}}" >> $GITHUB_OUTPUT
          echo "REPORT_PATH=$RUNNER_TEMP/report.json" >> $GITHUB_OUTPUT

      - name: Save logs
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.project}}-${{matrix.branch}}-logs
          path: "${{ steps.inspect-code.outputs.BUILD_DIR }}/resharper-*"

      - name: Upload reports'
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.project}}-${{matrix.branch}}-report
          path: "${{ steps.inspect-code.outputs.REPORT_PATH }}"
          retention-days: 1

  collect_reports:
    needs: run_correctness_test
    if: success() || failure()
    runs-on: ubuntu-22.04
    name: Collect reports

    steps:
    - uses: actions/checkout@v3

    - name: Clone report branch
      uses: actions/checkout@v3
      with:
        ref: "gh-pages"
        path: gh-pages

    - name: Download reports' artifacts
      uses: actions/download-artifact@v3
      with:
        path: downloaded_artifacts

    - name: (TEMP) Display structure of downloaded files
      run: ls -R
      working-directory: downloaded_artifacts

    - name: Update report
      shell: bash
      run: python .github/save_stats.py ./downloaded_artifacts $GITHUB_WORKSPACE/gh-pages

    - name: Commit report
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
