name: R++ runner

on: [push, pull_request]

env:
  RSCPP_VERSION: 2023.1.0

jobs:
  generate_matrix:
    name: Generate build matrix
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3

      - id: set-matrix
        run: python .github/build_projects_matrix.py ./projects.json ./proj-config >> $GITHUB_OUTPUT

  run_rscpp:
    needs: generate_matrix
    runs-on: ${{matrix.os}}
    name: Run R++ on ${{matrix.projects}} (${{matrix.cmake_gen}})

    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate_matrix.outputs.matrix)}}

    steps:
      - uses: actions/checkout@v3

      - name: Install R++
        run: dotnet tool update --global JetBrains.ReSharper.GlobalTools --version ${{ env.RSCPP_VERSION }}

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run correctness test
        shell: cmd
        run: |
          set VsInstallRoot=${{matrix.VsInstallRoot}}
          set VCTargetsPath=${{matrix.VCTargetsPath}}
          python CorrectnessTest.py ^
            --project ${{matrix.projects}} ^
            --vcpkg-dir %VCPKG_INSTALLATION_ROOT% ^
            --build-dir %USERPROFILE%\.dotnet\tools\.store\jetbrains.resharper.globaltools\${{ env.RSCPP_VERSION }}\jetbrains.resharper.globaltools\${{ env.RSCPP_VERSION }}\tools\netcoreapp3.1\any ^
            --projects-cache %RUNNER_TEMP%/projects ^
            --supported-generators ${{matrix.cmake_gen}} ^
            --verbose
